// AUTO-GENERATED by scripts/gen_globals_dts.py — elle düzenleme.
// Sadece HARİCİ global'ler (projede tanımlı olanlar tsserver tarafından
// included .js script-scope'tan zaten çözülür; burada bildirmek maskeler).
export {};
declare global {
  const supabase: any;
}
