#!/usr/bin/env python3
"""'.eslintrc.json' globals listesini types/globals.d.ts'e çevirir.
Tekrar çalıştırılabilir: eslint globals değişince yeniden üret.
Built-in LSP'nin global-fonksiyon mimarisinde cross-file çözümünü güçlendirir."""
import json
import sys
import pathlib


def _defined_in_js(repo: pathlib.Path, name: str) -> bool:
    """name js/ içinde top-level tanımlı mı? (function/const/let/var/class)
    Tanımlıysa globals.d.ts'e YAZMA — yoksa gerçek tanımı maskeler (goToDefinition bozulur)."""
    import re
    pat = re.compile(rf"^\s*(async\s+)?(function|const|let|var|class)\s+{re.escape(name)}\b", re.M)
    for f in (repo / "js").rglob("*.js"):
        try:
            if pat.search(f.read_text(encoding="utf-8")):
                return True
        except Exception:
            pass
    return False


def main(repo="/root/egesut-erp1"):
    repo = pathlib.Path(repo)
    all_names = sorted(json.loads((repo / ".eslintrc.json").read_text()).get("globals", {}).keys())
    # Sadece projede tanımlı OLMAYAN (gerçekten harici) global'leri bildir — maskeleme önlenir.
    external = [n for n in all_names if not _defined_in_js(repo, n)]
    skipped = [n for n in all_names if n not in external]
    lines = [
        "// AUTO-GENERATED by scripts/gen_globals_dts.py — elle düzenleme.",
        "// Sadece HARİCİ global'ler (projede tanımlı olanlar tsserver tarafından",
        "// included .js script-scope'tan zaten çözülür; burada bildirmek maskeler).",
        "export {};",
        "declare global {",
    ] + [f"  const {n}: any;" for n in external] + ["}"]
    out = repo / "types" / "globals.d.ts"
    out.parent.mkdir(exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print(f"✓ {out} — {len(external)} harici global yazıldı, {len(skipped)} proje-tanımlı atlandı")
    print(f"  atlanan (proje-tanımlı): {', '.join(skipped)}")
    print(f"  yazılan (harici): {', '.join(external)}")


if __name__ == "__main__":
    main(*sys.argv[1:])
