-- Canlı katalogdan public + surum_gizli şemaları için DDL deyimleri üretir (SALT-OKUNUR).
-- surum_gizli: degisim_geri_al (UI geri alma yolu) bunun 4 tablosuna + 12 fonksiyonuna bağımlı
-- (bkz. public.degisim_geri_al / degisim_onizle / geri_alma_bileti_al / sahip_sifresi_ayarla).
-- Çıktı: tek satır JSON dizi [{phase, ord, kind, name, sql}, ...]
-- search_path=pg_catalog → tüm tip/tablo/opclass adları şemayla nitelenir.
set search_path to pg_catalog;
with
schemas(nspname) as (values ('public'), ('surum_gizli')),
-- surum_gizli canlıda var (public her zaman var); yoksa önce yaratılmalı.
s_schema as (
  select 5 phase, s.nspname::text ord, 'schema'::text kind, s.nspname::text name,
    format('CREATE SCHEMA IF NOT EXISTS %I;', s.nspname) sql
  from schemas s where s.nspname <> 'public'
),
nsprel as (
  select n.oid nsp_oid, n.nspname
  from pg_namespace n join schemas s on s.nspname = n.nspname
),
pubrel as (
  select c.*, n.nspname,
    (case when n.nspname = 'public' then c.relname::text else n.nspname || '.' || c.relname end) as qn
  from pg_class c join nsprel n on n.nsp_oid = c.relnamespace
),
fnrel as (
  select p.*, n.nspname,
    (case when n.nspname = 'public' then p.proname::text else n.nspname || '.' || p.proname end) as qn
  from pg_proc p join nsprel n on n.nsp_oid = p.pronamespace
),
s_seq as (
  select 20 phase, c.qn ord, 'sequence'::text kind, c.qn name,
    format('CREATE SEQUENCE %I.%I AS %s INCREMENT BY %s MINVALUE %s MAXVALUE %s START WITH %s CACHE %s%s;',
      c.nspname, c.relname, format_type(s.seqtypid, null), s.seqincrement, s.seqmin, s.seqmax, s.seqstart, s.seqcache,
      case when s.seqcycle then ' CYCLE' else '' end) sql
  from pubrel c join pg_sequence s on s.seqrelid = c.oid
  where c.relkind = 'S'
    and not exists (select 1 from pg_depend d where d.classid = 'pg_class'::regclass and d.objid = c.oid and d.deptype = 'i')
),
s_tab as (
  select 30, c.qn, 'table', c.qn,
    format('CREATE TABLE %I.%I (%s)%s;', c.nspname, c.relname,
      coalesce(string_agg(
        format('%I %s%s%s', a.attname, format_type(a.atttypid, a.atttypmod),
          case a.attidentity when 'a' then ' GENERATED ALWAYS AS IDENTITY'
                             when 'd' then ' GENERATED BY DEFAULT AS IDENTITY' else '' end
          || case when a.attgenerated = 's' then ' GENERATED ALWAYS AS (' || pg_get_expr(ad.adbin, ad.adrelid) || ') STORED' else '' end,
          case when a.attnotnull then ' NOT NULL' else '' end),
        ', ' order by a.attnum) filter (where a.attnum is not null), ''),
      case when c.reloptions is not null then ' WITH (' || array_to_string(c.reloptions, ', ') || ')' else '' end)
  from pubrel c
  left join pg_attribute a on a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped
  left join pg_attrdef ad on ad.adrelid = a.attrelid and ad.adnum = a.attnum
  where c.relkind = 'r'
  group by c.oid, c.nspname, c.relname, c.qn, c.reloptions
),
s_fn as (
  select 40, p.qn || '(' || pg_get_function_identity_arguments(p.oid) || ')', 'function',
    p.qn || '(' || pg_get_function_identity_arguments(p.oid) || ')',
    pg_get_functiondef(p.oid) || ';'
  from fnrel p where p.prokind in ('f', 'p', 'w')
),
s_view as (
  select 50, c.qn, 'view', c.qn,
    format('CREATE VIEW %I.%I%s AS %s', c.nspname, c.relname,
      case when c.reloptions is not null then ' WITH (' || array_to_string(c.reloptions, ', ') || ')' else '' end,
      pg_get_viewdef(c.oid))
  from pubrel c where c.relkind = 'v'
),
s_def as (
  select 55, c.qn || '.' || a.attname, 'default', c.qn || '.' || a.attname,
    format('ALTER TABLE %I.%I ALTER COLUMN %I SET DEFAULT %s;', c.nspname, c.relname, a.attname, pg_get_expr(ad.adbin, ad.adrelid))
  from pg_attrdef ad join pubrel c on c.oid = ad.adrelid
  join pg_attribute a on a.attrelid = ad.adrelid and a.attnum = ad.adnum
  where a.attgenerated = '' and c.relkind in ('r', 'v')
),
s_seqown as (
  select 56, c.qn, 'seq_owned', c.qn,
    format('ALTER SEQUENCE %I.%I OWNED BY %I.%I.%I;', c.nspname, c.relname, tn.nspname, t.relname, a.attname)
  from pg_depend d join pubrel c on c.oid = d.objid
  join pg_class t on t.oid = d.refobjid
  join pg_namespace tn on tn.oid = t.relnamespace
  join pg_attribute a on a.attrelid = t.oid and a.attnum = d.refobjsubid
  where d.classid = 'pg_class'::regclass and d.refclassid = 'pg_class'::regclass and d.deptype = 'a' and c.relkind = 'S'
),
s_con as (
  select case when co.contype = 'f' then 70 else 60 end, c.qn || '.' || co.conname, 'constraint_' || co.contype::text,
    c.qn || '.' || co.conname,
    format('ALTER TABLE %I.%I ADD CONSTRAINT %I %s;', c.nspname, c.relname, co.conname, pg_get_constraintdef(co.oid))
  from pg_constraint co join pubrel c on c.oid = co.conrelid
  where co.contype in ('p', 'u', 'c', 'f', 'x')
),
s_idx as (
  select 65, ic.qn, 'index', ic.qn, pg_get_indexdef(i.indexrelid) || ';'
  from pg_index i join pubrel ic on ic.oid = i.indexrelid
  where not exists (select 1 from pg_constraint co where co.conindid = i.indexrelid and co.contype in ('p', 'u', 'x'))
),
s_trg as (
  select 80, c.qn || '.' || t.tgname, 'trigger', c.qn || '.' || t.tgname,
    pg_get_triggerdef(t.oid, false) || ';' ||
    case t.tgenabled when 'D' then format(' ALTER TABLE %I.%I DISABLE TRIGGER %I;', c.nspname, c.relname, t.tgname)
                     when 'R' then format(' ALTER TABLE %I.%I ENABLE REPLICA TRIGGER %I;', c.nspname, c.relname, t.tgname)
                     when 'A' then format(' ALTER TABLE %I.%I ENABLE ALWAYS TRIGGER %I;', c.nspname, c.relname, t.tgname)
                     else '' end
  from pg_trigger t join pubrel c on c.oid = t.tgrelid
  where not t.tgisinternal
),
s_rls as (
  select 85, c.qn, 'rls', c.qn,
    format('ALTER TABLE %I.%I ENABLE ROW LEVEL SECURITY;', c.nspname, c.relname) ||
    case when c.relforcerowsecurity then format(' ALTER TABLE %I.%I FORCE ROW LEVEL SECURITY;', c.nspname, c.relname) else '' end
  from pubrel c where c.relkind = 'r' and c.relrowsecurity
),
s_pol as (
  select 86, c.qn || '.' || p.polname, 'policy', c.qn || '.' || p.polname,
    format('CREATE POLICY %I ON %I.%I AS %s FOR %s TO %s%s%s;', p.polname, c.nspname, c.relname,
      case when p.polpermissive then 'PERMISSIVE' else 'RESTRICTIVE' end,
      case p.polcmd when 'r' then 'SELECT' when 'a' then 'INSERT' when 'w' then 'UPDATE' when 'd' then 'DELETE' else 'ALL' end,
      (select string_agg(case when r = 0 then 'PUBLIC' else quote_ident(pg_get_userbyid(r)) end, ', ') from unnest(p.polroles) r),
      coalesce(' USING (' || pg_get_expr(p.polqual, p.polrelid) || ')', ''),
      coalesce(' WITH CHECK (' || pg_get_expr(p.polwithcheck, p.polrelid) || ')', ''))
  from pg_policy p join pubrel c on c.oid = p.polrelid
),
s_cmt as (
  select 90, c.qn, 'comment', c.qn,
    format('COMMENT ON %s %I.%I IS %L;', case c.relkind when 'v' then 'VIEW' when 'S' then 'SEQUENCE' else 'TABLE' end, c.nspname, c.relname, d.description)
  from pg_description d join pubrel c on c.oid = d.objoid and d.classoid = 'pg_class'::regclass and d.objsubid = 0
  where c.relkind in ('r', 'v', 'S')
  union all
  select 90, c.qn || '.' || a.attname, 'comment', c.qn || '.' || a.attname,
    format('COMMENT ON COLUMN %I.%I.%I IS %L;', c.nspname, c.relname, a.attname, d.description)
  from pg_description d join pubrel c on c.oid = d.objoid and d.classoid = 'pg_class'::regclass
  join pg_attribute a on a.attrelid = c.oid and a.attnum = d.objsubid
  where d.objsubid > 0
  union all
  select 90, p.qn, 'comment', p.qn,
    format('COMMENT ON FUNCTION %I.%I(%s) IS %L;', p.nspname, p.proname, pg_get_function_identity_arguments(p.oid), d.description)
  from pg_description d join fnrel p on p.oid = d.objoid and d.classoid = 'pg_proc'::regclass
),
-- Yetkiler: yalnız PUBLIC / anon / authenticated / service_role (Supabase API rolleri)
acl_rel as (
  select c.qn as qn, c.nspname as nspname, c.relname as bare_relname, c.relkind as relkind, x.grantee as grantee, x.privilege_type as privilege_type
  from pubrel c, aclexplode(c.relacl) x
  where c.relkind in ('r', 'v', 'S')
    and (x.grantee = 0 or pg_get_userbyid(x.grantee) in ('anon', 'authenticated', 'service_role'))
),
s_grant_rel as (
  select 92, qn, 'grant', qn,
    format('GRANT %s ON %s %I.%I TO %s;', string_agg(privilege_type, ', ' order by privilege_type),
      case when relkind = 'S' then 'SEQUENCE' else 'TABLE' end, nspname, bare_relname,
      case when grantee = 0 then 'PUBLIC' else quote_ident(pg_get_userbyid(grantee)) end)
  from acl_rel group by qn, nspname, bare_relname, relkind, grantee
),
s_grant_fn as (
  select 92, p.qn || '(' || pg_get_function_identity_arguments(p.oid) || ')', 'grant',
    p.qn || '(' || pg_get_function_identity_arguments(p.oid) || ')',
    format('REVOKE ALL ON FUNCTION %I.%I(%s) FROM PUBLIC;', p.nspname, p.proname, pg_get_function_identity_arguments(p.oid)) ||
    coalesce((select string_agg(format(' GRANT EXECUTE ON FUNCTION %I.%I(%s) TO %s;', p.nspname, p.proname,
                pg_get_function_identity_arguments(p.oid),
                case when x.grantee = 0 then 'PUBLIC' else quote_ident(pg_get_userbyid(x.grantee)) end), '')
              from aclexplode(p.proacl) x
              where x.privilege_type = 'EXECUTE'
                and (x.grantee = 0 or pg_get_userbyid(x.grantee) in ('anon', 'authenticated', 'service_role'))), '')
  from fnrel p
  where p.proacl is not null
),
s_cron as (
  select 95, j.jobname, 'cron', j.jobname,
    format('SELECT cron.schedule(%L, %L, %L);', j.jobname, j.schedule, j.command)
  from cron.job j
),
allrows(phase, ord, kind, name, sql) as (
  select * from s_schema union all
  select * from s_seq union all select * from s_tab union all select * from s_fn
  union all select * from s_view union all select * from s_def union all select * from s_seqown
  union all select * from s_con union all select * from s_idx union all select * from s_trg
  union all select * from s_rls union all select * from s_pol union all select * from s_cmt
  union all select * from s_grant_rel union all select * from s_grant_fn union all select * from s_cron
)
select coalesce(json_agg(json_build_object('phase', phase, 'ord', ord, 'kind', kind, 'name', name, 'sql', sql)
         order by phase, ord), '[]'::json) as ddl
from allrows;
